#!/bin/sh

idgen() { head -c $1 /dev/urandom | base64; }

mkdir ~/.komichi 2> /dev/null

soup_base="https://w3.komisanwamanga.com"
counter=0

session_file="$(idgen 6).txt"
home_pg=$(curl -s "$soup_base")
chpts_links=$(echo "$home_pg" | grep -o "<a href=\"$soup_base/manga/.*/\">.*<")
rlimit=$(($(echo "$chpts_links" | wc -l) - 5))
pretty_links=$(echo "$chpts_links" | awk "NR <= $rlimit" | tac)

# Chapter links
clchpt_links=$(echo "$pretty_links" | sed -E "s/<a href=|\"|>.*//g")

# Chapter names
cname_links=$(echo "$pretty_links" | sed -E -e "s/<a href=\"[^\"]*\">|<\/a><//g" -e "s/&#8217;/'/g" -e "s/&#8211\;/-/g" -e "s/&#038\;/&/g" > ~/.komichi/$session_file)

while IFS= read line; do
	counter=$((counter + 1))
	printf "\033[1;34m[${counter}] \033[1;36m${line}\033[0m\n"
done < ~/.komichi/$session_file

rm ~/.komichi/$session_file 2> /dev/null

echo "\n\033[1;33mTo download specific range of chapters (choices), use this format 'start_chapter end_chapter'. Example: 47 55\033[0m"

while true; do
	echo -n "\n\033[1;35mPlease choose the chapter [1-${counter}]: \033[0m"
	read start end

	if [ -z $end ]; then
		if [ $start -eq $start ] 2> /dev/null; then
			if [ $start -gt $counter ] || [ $start -lt 1 ]; then
				echo "\n\033[1;31mThere is no the ${start}th chapter\033[0m"
				continue
			fi

			break

		else
			echo '\n\033[1;31mPlease input valid number\033[0m'
			continue
		fi

	elif ! [ -z $end ]; then
		if [ $start -eq $start ] 2> /dev/null && [ $end -eq $end ] 2> /dev/null; then			true
		fi

	fi

done
